// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4e1kHDGXCa52YT1d4j1gbzFeMHuhgnXs',
    appId: '1:387895461581:web:ffc6e109d8e4d228c4cb84',
    messagingSenderId: '387895461581',
    projectId: 'flutter1-68afc',
    authDomain: 'flutter1-68afc.firebaseapp.com',
    storageBucket: 'flutter1-68afc.firebasestorage.app',
    measurementId: 'G-PMK52Y81LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWI6vHpNt9FsW0Ye5KTrDV8o6vpeL4LG0',
    appId: '1:387895461581:android:f1d49ffd015e2223c4cb84',
    messagingSenderId: '387895461581',
    projectId: 'flutter1-68afc',
    storageBucket: 'flutter1-68afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXceefXD4myErGj3HDHVZp5LEjjHvUsXw',
    appId: '1:387895461581:ios:e1cd3cfeeb43afabc4cb84',
    messagingSenderId: '387895461581',
    projectId: 'flutter1-68afc',
    storageBucket: 'flutter1-68afc.firebasestorage.app',
    iosClientId: '387895461581-icdb0cs3nuf6er76uk1s7bmh5nt9gnh5.apps.googleusercontent.com',
    iosBundleId: 'com.learners.learners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXceefXD4myErGj3HDHVZp5LEjjHvUsXw',
    appId: '1:387895461581:ios:e1cd3cfeeb43afabc4cb84',
    messagingSenderId: '387895461581',
    projectId: 'flutter1-68afc',
    storageBucket: 'flutter1-68afc.firebasestorage.app',
    iosClientId: '387895461581-icdb0cs3nuf6er76uk1s7bmh5nt9gnh5.apps.googleusercontent.com',
    iosBundleId: 'com.learners.learners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4e1kHDGXCa52YT1d4j1gbzFeMHuhgnXs',
    appId: '1:387895461581:web:215a054a9acb10d6c4cb84',
    messagingSenderId: '387895461581',
    projectId: 'flutter1-68afc',
    authDomain: 'flutter1-68afc.firebaseapp.com',
    storageBucket: 'flutter1-68afc.firebasestorage.app',
    measurementId: 'G-XXPKCBQPY4',
  );

}